# Generated by Django 4.2.7 on 2023-11-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='CarModel name')),
                ('price', models.PositiveIntegerField(verbose_name='CarModel price')),
                ('img', models.ImageField(upload_to='images', verbose_name='CarModel image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_categ', to='main.category')),
            ],
        ),
    ]
